site_name: CATIMA
site_url: https://catima.unil.ch
site_description: CATIMA - créateur de catalogues interactifs
site_author: Université de Lausanne - Christian Kaiser

pages:
  - Français:
    - Accueil: index.md
    - Mode d'emploi: user-guide/index.md

copyright: Copyright &copy; 2017 <a href="https://unil.ch">Université de Lausanne</a>

